sudo: required

language: ruby

services:
  - docker

before_script:
  - docker-compose up --build -d
  - docker ps -a
  - sleep 30  # wait for PostgreSQl to start
  - docker-compos run api rake db:migrate

script:
  - ./tests/source-checks.sh

after_script:
  - docker-compose down
