sudo: required

language: ruby

services:
  - docker

before_script:
  - cp dev.env .env
  - docker-compose up --build -d
  - docker ps -a
  - docker-compose run api rake db:migrate

script:
  - ./tests/source-checks.sh

after_script:
  - docker-compose down
