version: '3'

services:
  frontend:
    command: yarn start
    build: ./frontend
    ports:
      - '8000:8000'
    volumes:
      - './frontend:/app'
  api:
    volumes:
      - './api:/app'
  db:
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
