version: '3'

services:
  db:
    image: 'postgres:10.5-alpine'
    volumes:
      - 'tapp-db-data:/var/lib/postgresql/data'
    env_file:
      - './api/.env'
  api:
    depends_on:
      - 'db'
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    build: ./api
    ports:
      - '3023:3000'
    volumes:
      - './api:/app'
    env_file:
      - './api/.env'
  frontend:
    command: yarn start
    build: ./frontend
    ports:
      - '8000:8000'
    volumes:
      - './frontend:/app'

volumes:
  tapp-db-data:
    driver: local
