AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/{assets,tasks}/*'
    - 'test/**/*'
    - 'frontend/**/**'
    - 'script/**/**'
    - 'resources/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 500

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false
